---
title: MaW Media Schema ERD
---
erDiagram
    %% external_id = nameidentifier
    external_identity {
        TEXT external_id PK
        UUID user_id FK
        TIMESTAMPTZ created
        TIMESTAMPTZ modified
        TEXT name
        TEXT email
        BOOLEAN email_verified
        TEXT given_name
        TEXT surname
        TEXT picture
    }

    user {
        UUID id PK
        TIMESTAMPTZ created
        TIMESTAMPTZ modified
        TEXT name
        TEXT email
        BOOLEAN email_verified
        TEXT given_name
        TEXT surname
        TEXT picture
    }

    role {
        UUID id PK
        TEXT name UK
    }

    user_role {
        UUID user_id PK, FK
        UUID role_id PK, FK
    }

    category {
        UUID id PK
        TEXT NAME
        UUID teaser_media_id FK
        DATE effective_date
        TIMESTAMPTZ created
        UUID created_by FK
        TIMESTAMPTZ modified
        UUID modified_by FK
    }

    media_role {
        UUID media_id PK, FK
        UUID role_id PK, FK
    }

    media_type {
        UUID id PK
        TEXT name UK
    }

    media {
        UUID id PK
        UUID category_id FK
        UUID media_type_id FK
        UUID location_id FK
        UUID location_override_id FK
        TIMESTAMPTZ created
        UUID created_by FK
        TIMESTAMPTZ modified
        UUID modified_by FK
        JSONB metadata
        NUMERIC(7_2) duration_seconds
    }

    location {
        UUID id PK
        NUMERIC(8_6) latitude
        NUMERIC(9_6) longitude
        TIMESTAMPTZ lookup_date
        TEXT formatted_address
        TEXT administrative_area_level_1
        TEXT administrative_area_level_2
        TEXT administrative_area_level_3
        TEXT country
        TEXT locality
        TEXT neighborhood
        TEXT sub_locality_level_1
        TEXT sub_locality_level_2
        TEXT postal_code
        TEXT postal_code_suffix
        TEXT premise
        TEXT route
        TEXT street_number
        TEXT sub_premise
    }

    point_of_interest {
        UUID location_id PK, FK
        TEXT type PK
        TEXT name
    }

    %% qqvg    ( 160 x  120)
    %% qvg     ( 320 x  240)
    %% nhd     ( 640 x  360)
    %% hd      (1280 x  720)
    %% full_hd (1920 x 1080)
    %% qhd     (2560 x 1440)
    %% 4k      (3840 x 2160)
    %% 5k      (5120 x 2880)  - skip for now
    %% 8k      (7680 × 4320)  - skip for now
    %% src     ?
    media_scale {
        UUID id PK
        TEXT abbreviation UK
        TEXT name UK
        INTEGER max_width
        INTEGER max_height
        BOOLEAN is_square_cropped
    }

    scaled_media {
        UUID media_id PK, FK
        UUID media_scale_id PK, FK
        UUID media_type_id PK, FK
        INTEGER height
        INTEGER width
        INTEGER bytes
        TEXT path
    }

    comment {
        UUID id PK
        TIMESTAMPTZ created
        UUID created_by FK
        TIMESTAMPTZ modified
        TEXT body
    }

    rating {
        UUID id PK
        TIMESTAMPTZ created
        UUID user_id FK
        TIMESTAMPTZ modified
        SMALLINT rating
    }

    external_identity }o--|| user : ""
    user ||--o{ user_role : ""
    role ||--o{ user_role : ""

    category }o--|| user : ""
    category }o--o| media : ""

    %% assign perms here to allow flexibility of showing/hiding media on a per role basis
    media_role }o--|| role : ""

    media }o--|| category : ""
    media }o--|| media_type : ""
    media ||--o{ media_role : ""
    media ||--o{ comment: ""
    media ||--o{ rating: ""
    media }o--o| location : ""

    location ||--o{ point_of_interest : ""
    comment }o--|| user : ""
    rating }o--|| user : ""

    scaled_media ||--o{ media : ""
    scaled_media }o--|| media_scale : ""
    scaled_media }o--|| media_type : ""
