###
http://localhost:5000/categories/years

###
http://localhost:5000/categories/years/2022

###
http://localhost:5000/categories

###
http://localhost:5000/categories/updates/2022-11-05

### (invalid category)
http://localhost:5000/categories/21977b3a-6db7-7eda-96c0-21c853957389

### (valid category)
http://localhost:5000/categories/01977b3a-6db7-7eda-96c0-21c853957389

### (invalid category - todo: return notfound)
http://localhost:5000/categories/21977b3a-6db7-7eda-96c0-21c853957389/media

###
http://localhost:5000/categories/01977b3a-6db7-7eda-96c0-21c853957389/media

### (invalid category)
POST http://localhost:5000/categories/21977b3a-6db7-7eda-96c0-21c853957389/favorite
Content-Type: application/json

{
    "isFavorite": false
}

###
POST http://localhost:5000/categories/01977b3a-6db7-7eda-96c0-21c853957389/favorite
Content-Type: application/json

{
    "isFavorite": false
}

### (invalid media)
POST http://localhost:5000/categories/01977b3a-6db7-7eda-96c0-21c853957389/teaser
Content-Type: application/json

{
    "mediaId": "01977b3a-6db7-7eda-96c0-21c853957389"
}

### (valid media)
POST http://localhost:5000/categories/01977b3a-6db7-7eda-96c0-21c853957389/teaser
Content-Type: application/json

{
    "mediaId": "01977b3a-79bd-74fb-ad5c-0abe0b51be92"
}

### (valid category - no gps)
http://localhost:5000/categories/01977b3a-6db7-7eda-96c0-21c853957389/gps

### (valid category - no gps)
http://localhost:5000/categories/01977b3a-6db5-7888-b10e-aa51e147ecc7/gps

###
http://localhost:5000/categories/search?s=friend
