<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>MawMedia.Services.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="test-down.sh" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="test-up.sh" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CliWrap" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Npgsql.NodaTime" />
        <PackageReference Include="xunit.v3.mtp-v2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MawMedia\MawMedia.csproj" />
        <ProjectReference Include="..\..\src\MawMedia.Services\MawMedia.Services.csproj" />
    </ItemGroup>

</Project>
