<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="NodaTime.Serialization.SystemTextJson" />
        <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MawMedia.Models\MawMedia.Models.csproj" />
        <ProjectReference Include="..\MawMedia.Services.Abstractions\MawMedia.Services.Abstractions.csproj" />
    </ItemGroup>

</Project>
