name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IID_FILE: image.iid

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: build container image
        run: |
          buildah bud \
            -f Containerfile \
            -t maw-media \
            --iidfile "$IID_FILE"

      - name: populate image id variable
        run: echo "IID=$(cat $IID_FILE)" >> "$GITHUB_ENV"

      - name: compute tag
        id: tag
        run: echo "value=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: log in to docker hub
        env:
          DH_USER: ${{ secrets.DH_USER }}
          DH_PASS: ${{ secrets.DH_PASS }}
        run: echo "$DH_PASS" | buildah login -u "$DH_USER" --password-stdin docker.io

      - name: push image with specific tag
        run: |
          buildah push \
            "${IID}" \
            docker://aerisg222/maw-media:"${{ steps.tag.outputs.value }}"

      - name: push image with latest tag
        run: |
          buildah push \
            "${IID}" \
            docker://aerisg222/maw-media:latest
